language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE ttci;'
  - php -f init.php
script:
  - php -f test.php
  - phpunit --version
#  - cd tests; php codecept.phar run
