language: php
dist: trusty
sudo: required
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
services:
  - mysql
  - memcache
  - memcached
before_install:
  - mysql -e 'CREATE DATABASE ttci;'
  - php -f init.php
before_script:
  # test apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  # - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  # - sudo ls -la /home/travis/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f .travis-apache.conf /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  #
  # test extensions
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # ^^^ OK
  # - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # ^^^ PHP Warning:  PHP Startup: Unable to load dynamic library 'memcache.so' ...
  - echo 'y' | pecl install memcache
script:
  - php -f test.php
  - phpunit --version
  # - cd tests; php codecept.phar --version; cd ..
  - cd tests
  - php codecept.phar run
  - cd ..
  - php -f testweb.php
  - php -f testweb.php
  # test extensions
  - php -f testext.php
